### ISSUE TITLE
Merge similar projects into one

### ISSUE THREAD

**Issue by gamelaster** [jdan/98.css#106]
Since there are two great forks (XP and 7 one), I think it would be amazing, to have all this in one CSS library, with same controls/widgets, same class names etc.

**Comment by trumad** [comment]
Where's the windows 7 one? Can you provide a link? I found the [XP one](https://botoxparty.github.io/XP.css/).

**Comment by gamelaster** [comment]
@trumad [here](https://khang-nd.github.io/7.css/)

**Comment by jdan** [comment]
I like the idea in principle but my big concern is that I want the two

authors to have proper attribution for their work - like they do now
from their GitHub profiles.

But a strong +1 to normalizing APIs :)

On February 15, 2021, GitHub <notifications@github.com> wrote:
> @trumad <https://github.com/trumad>
> here <https://khang-nd.github.io/7.css/>
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jdan/98.css/issues/106#issuecomment-779261467>, or

unsubscribe <https://github.com/notifications/unsubscribe-
auth/AACGEJEKG33KJIP3ZU6YMTTS7EWM7ANCNFSM4XSNKIXQ>.

**Comment by gamelaster** [comment]
@jdan thanks for reply and for supporting of this idea.

@botoxparty and @khang-nd what's your ideas? it would be really cool to have! 😊

**Comment by botoxparty** [comment]
Hey! I've always wanted something like this to happen. I guess this was my intention with splitting it into GUI.css to make it easier to create new skins.

@jdan In terms of attribution I certainly wouldn't let my ego get in the way of the project continuing further, this is OSS.

My main concern with the project is that it will need better structure and support in terms of the documentation, the way that the docs pages are currently generated isn't very scalable. We would need some kind of one-size-fits-all solution that will also allow for further themes.

I would love to see some other variants; how i imagine it could grow:

GUI.css
 - Windows.css
     - 98.css
     - XP.css
     - 7.css
 - MacOS.css
     - OS9.css
     - Aqua.css

@gamelaster Dare to take on a MacOS variant? 😉

**Comment by gamelaster** [comment]
Hi @botoxparty , thank you for fast response. Your propose of support of various themes is great, would be really nice to open "the doors" to other contributors.

About making MacOS variant, I probably would able to do that, although, I'm kinda busy and I'm not using MacOS a lot, so probably I will left this to someone else.

Anyway, I will try to track this idea and effort, and participate with something in my free time schedule.

Thanks guys.

**Comment by khang-nd** [comment]
+1 from my side. Though I don't have an idea how these should be merged and maintained in a way that takes as little effort as possible. Either someone is willing to spend the time to sync up the 3 projects separately, or create a new centralized project and do it there, all fine to me 👌

**Comment by gamelaster** [comment]
By my opinion, making new repo, like `native-gui.css` or something like that would be amazing. About what needs to be done, your Windows 7 CSS have most components available, so I guess it will be required to finish some components on 98 and XP variant, to have same count of components for every variant.

**Comment by rashil2000** [comment]
Looking forward to this!! 

It'd be really cool to have a dropdown available to we can switch the 98, XP and 7 styles instantly! ([botoxparty.github.io/XP.css](https://botoxparty.github.io/XP.css/) already has this)

**Comment by IamRifki** [comment]
@botoxparty Your comment made me do some digging and apparently there's someone who already made an OS9-style CSS UI library https://github.com/Tecate/os9css. I tried "standardising" it inline with the rest of the UI libraries, but it's still not perfect due to how complete the library is and how different OS9 was to Windows https://github.com/IamRifki/OS9.css.

Hopefully someone who has more will than me can work on a better version.

**Comment by jdan** [comment]
Probably not going to do this :)
