### ISSUE TITLE
border-style inset/outset

### ISSUE THREAD

**Issue by JannesMeyer** [jdan/98.css#15]
Hi,

I saw this posted on Hacker News and I was wondering why you use `box-shadow` for the "3D effect" on buttons and window borders instead of `border-style: outset`. Is there a technical reason for it?

I think the box-shadow version makes it look a bit softer than it was in Windows 98.

**Comment by jdan** [comment]
Hey! I went with box-shadow because it was the best way I could come up with to match this "staircase" border style from Windows 98.

<img width="200" src="https://user-images.githubusercontent.com/287268/79997016-19693c80-8487-11ea-9c91-b1b2819dfc2b.png">

I experimented with `::after` and some border hacks but this seemed more intuitive. If `border-style` can help here I'd love to see!
