### ISSUE TITLE
White background and overflow with 98.css elements since recent preview build

### ISSUE THREAD

**Issue by Dennogin** [jdan/98.css#161]
I've been using the unpkg build of 98.css since last year with no issues, but today it seems like something broke with the public build as elements I use with 98.css appear buggy and glitched out. Every element has a white background, and there also seems to be an issue with the text formatting.
Is this an error on my part or was this an error with the recent preview build? This also happens whether or not I'm running it locally or on the actual webserver.
![image](https://user-images.githubusercontent.com/111214335/224583406-7d25c531-b2f0-40f6-96f7-be7c69e24211.png)

**Comment by Dennogin** [comment]
After pointing the stylesheet ref directly to the previous version 
`<link rel="stylesheet" href="https://unpkg.com/98.css@0.1.18/dist/98.css">`
It works like it used to, if anyone else is experiencing the same issue this workaround seems to work fine.

**Comment by jdan** [comment]
Thanks for reporting, can I have a link to your implementation? I’d love
to spot check any differences from 0.1.18

On March 12, 2023, Mads Hougesen ***@***.***> wrote:
> After pointing the stylesheet ref directly to the previous version
>  <link rel="stylesheet"
> ***@***.***/dist/98.css">
>  It works like it used to, if anyone else is experiencing the same
> issue this workaround seems to work fine.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/jdan/98.css/issues/161#issuecomment-1465349836>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AACGEJAWGNEWTL2VJNMPAG3W3Z3LZANCNFSM6AAAAAAVYNU7ZQ>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by Dennogin** [comment]
Sure thing, just a warning I take the old geocities website design very head-on :)
https://bonahnsa.com/index.html

**Comment by jdan** [comment]
Sorry about that @Dennogin! As of https://github.com/jdan/98.css/pull/151 we're adding some styles to the top-level `table`

For your use-case you can add the following rules to your CSS upon upgrading to the latest version of 98.css.

```
table {
  background-color: inherit;
  white-space: normal;
}
```
