### ISSUE TITLE
Firefox fails to render group box border

### ISSUE THREAD

**Issue by RobThaBlob** [jdan/98.css#42]
On Firefox, the group box border does not render.

**Comment by jdan** [comment]
Is this still happening for you? https://jdan.github.io/98.css/#group-box

I see them on 77.0.1

**Comment by RobThaBlob** [comment]
Jordan,

Yes, I'm afraid it's still happening.

[image: image.png]

Regards,

Rob

**Comment by RobThaBlob** [comment]
Jordan,

I'm afraid I snipped the wrong image...

[image: image.png]
Regards,

Rob

**Comment by jdan** [comment]
@RobThaBlob sorry, the image doesn't appear to be attaching for me. you may need to comment from the github interface. could you let me know which version of firefox you're running?

**Comment by DannyJJK** [comment]
This happens to me as well, Firefox 89 on macOS Big Sur. Works fine on Chrome.

<img width="1226" alt="imagen" src="https://user-images.githubusercontent.com/11057501/120548824-b7e60200-c3ea-11eb-9526-0ab577a71d38.png">

**Comment by dwhinham** [comment]
I figured out that it seems to be caused by a bug in Firefox's new WebRender engine, which started being enabled by default for Windows users since Firefox 78, and for other OSes/hardware configurations gradually over time.

If I set `gfx.webrender.force-disabled` to `true` in `about:config`, the GroupBox borders reappear for me in Firefox 90.0.2 (Linux).

I think this open Mozilla bug is probably related: https://bugzilla.mozilla.org/show_bug.cgi?id=1496538

I've opened #117 to provide a workaround for this. Basically instead of an inset `box-shadow`, we create a tiny .SVG image like this, similar how some of the other widgets are done:
![98groupbox](https://user-images.githubusercontent.com/5890747/128520526-9c8e14b9-bf8e-496b-87ed-78e483620f2f.png)

Then we can use `border-image` with a slice value of 2 to create the border effect. This is how it looks under Firefox 90.0.2 and Chromium 92.0.4515.131:
![2021-08-06-143958_1911x2118_scrot](https://user-images.githubusercontent.com/5890747/128520720-c0bea760-26c6-4337-b52a-acb779b7f88c.png)

Thanks to the very cool Vercel integration, you can test this approach here: https://98css-git-fork-dwhinham-fix-42-jdan.vercel.app/

Cheers! 🙂
