### ISSUE TITLE
Padding on radios and checkbox on mobile Safari

### ISSUE THREAD

**Issue by jdan** [jdan/98.css#61]
![image](https://user-images.githubusercontent.com/287268/80284619-9eee2600-86ed-11ea-8c8b-42a49f8ca6ba.png)

**Comment by okoflo** [comment]
Is there a bit more information on this issue? 😄 

I read through the previous issue #5 , but I'm not sure what I should be looking for on this issue specifically.

**Comment by nathan-a-macleod** [comment]
@jdan I think the issue is that the checkboxes are about 5px or so to the right. Is this what the issue is talking about?

By the way, a username called 'jacob-and-nathan' (renamed to 'jacob-macleod') did some pull requests, etc - I have changed the GitHub account to this one, so please use this account instead.

**Comment by jdan** [comment]
Seems fixed :)
